[client_folder]
inputs = /path/to/GRS
output = /path/to/output
wmask_folder = /path/to/water_masks

[vector_list]
roi_vectors = /path/to/shp/liangzi_lake_epsg32650.shp

[processing]
ac_processor = GRS
# options are: GRS or ACOLITE
compute_l2b = True
make_report = True
report_rrs = True
parallel = True
s2_tile = 50RKU
s2_resolution = 20
grs_version = v20
# grs_version options:
# v15, v20 (default) or v21 
# grs_version is ignored when ac_processor = ACOLITE

[timeseries]
l2b_algorithms = [
    # 'CDOM_Brezonik',
    ]
