[client_folder]
inputs = /path/to/your/L2A/
output = /path/to/your/GPK_out
wmask_folder = /path/to/your/water_masks

[vector_list]
roi_vectors = /path/to/your/roi_1.shp,
              /path/to/your/roi_2.shp

[processing]
# ac_processor can be GRS or ACOLITE
ac_processor = GRS
grs_version = v20
# grs_version options:
# v15, v20 (default) or v21 
# grs_version is ignored when ac_processor = ACOLITE
compute_l2b = True
make_report = True
report_rrs = True
parallel = True
s2_tile = 50RKU
s2_resolution = 20

[timeseries]
l2b_algorithms = [
    # 'CDOM_Brezonik',
    ]

[output_encoding]
encoding_version = GETPAK-ENC-2
rrs_multiplier = 10000
chla_multiplier = 100
turbidity_multiplier = 10
hyspm_multiplier = 10
continuous_dtype = uint16
continuous_nodata = 65535
categorical_dtype = uint8
categorical_nodata = 255
